[monitor:///var/log/sysmon/sysmon.json]
disabled = false
index = endpoint
sourcetype = sysmon:json

[monitor:///var/log/windows/security.json]
disabled = false
index = endpoint
sourcetype = winsec:json

[monitor:///var/log/aws/cloudtrail.json]
disabled = false
index = cloud
sourcetype = aws:cloudtrail:json

[monitor:///var/log/aws/guardduty.json]
disabled = false
index = cloud
sourcetype = aws:guardduty:json
