[sysmon:json]
INDEXED_EXTRACTIONS = json
KV_MODE = none
NO_BINARY_CHECK = true
TIME_PREFIX = "timestamp"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ

[winsec:json]
INDEXED_EXTRACTIONS = json
KV_MODE = none
NO_BINARY_CHECK = true
TIME_PREFIX = "timestamp"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ

[aws:cloudtrail:json]
INDEXED_EXTRACTIONS = json
KV_MODE = none
NO_BINARY_CHECK = true
TIME_PREFIX = "eventTime"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ

[aws:guardduty:json]
INDEXED_EXTRACTIONS = json
KV_MODE = none
NO_BINARY_CHECK = true
TIME_PREFIX = "updatedAt"\s*:\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
